version: "3.9"

networks:
  web:
    driver: bridge

volumes:
  moodle_app: {}
  moodle_data: {}
  pg_data: {}
  caddy_data: {}
  caddy_config: {}

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [web]
    mem_limit: 1g
    cpus: "0.70"

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [web]
    mem_limit: 256m
    cpus: "0.30"

  moodle:
    image: bitnami/moodle:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # ---- DB ----
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: "5432"
      MOODLE_DATABASE_NAME: ${POSTGRES_DB}
      MOODLE_DATABASE_USER: ${POSTGRES_USER}
      MOODLE_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}

      # ---- Initial admin (one-time) ----
      MOODLE_USERNAME: ${MOODLE_USERNAME}
      MOODLE_PASSWORD: ${MOODLE_PASSWORD}
      MOODLE_EMAIL: ${MOODLE_EMAIL}

      # ---- Site ----
      MOODLE_SITE_NAME: ${MOODLE_SITE_NAME}
      MOODLE_HOST: ${DOMAIN}
      ALLOW_EMPTY_PASSWORD: "no"
      TZ: ${TZ}
    volumes:
      - moodle_app:/bitnami/moodle
      - moodle_data:/bitnami/moodledata
    networks: [web]
    expose:
      - "8080"
    healthcheck:
      # Simple HTTP check against the container’s Apache
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
    mem_limit: 2g
    cpus: "0.90"

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      moodle:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"
      ACME_EMAIL: ${ACME_EMAIL}
      TZ: ${TZ}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks: [web]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:80/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
    mem_limit: 256m
    cpus: "0.30"
